
spring:
    datasource:
#        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:jhipstersampleapplication;DB_CLOSE_DELAY=-1
        username: jhipsterSampleApplication
        password:
    h2:
      console:
        enabled: true
logging:
  level:
    ROOT: debug